### ISSUE TITLE
Tailwindcss doc can't yarn install

### ISSUE THREAD

**Issue by ansharw** [naveennamani/offline-docs#1]
Thanks to the tutorial about offline documentation.
But, i want to install tailwindcss offline doc, but this error can stop me to the next step.
1. git clone https://github.com/tailwindlabs/tailwindcss.com.git
2. cd tailwindcss.com/
3. code .
4. yarn install 
=============== STOP ==============
build failed 

my version node,js, python
node = v16.14.2
node-gyp = v8.4.1
python = 3.10.5

The error like this :
$ yarn install
yarn install v1.22.15
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info @next/swc-darwin-arm64@11.1.4: The platform "win32" is incompatible with this module.
info "@next/swc-darwin-arm64@11.1.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-darwin-arm64@11.1.4: The CPU architecture "x64" is incompatible with this module.
info @next/swc-darwin-x64@11.1.4: The platform "win32" is incompatible with this module.
info "@next/swc-darwin-x64@11.1.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info @next/swc-linux-x64-gnu@11.1.4: The platform "win32" is incompatible with this module.
info "@next/swc-linux-x64-gnu@11.1.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @docsearch/react@3.1.0" has unmet peer dependency "@types/react@>= 16.8.0 < 19.0.0".
warning " > @next/mdx@10.2.3" has unmet peer dependency "@mdx-js/react@*".
warning " > @reach/rect@0.10.5" has incorrect peer dependency "react@^16.8.0".
warning " > @reach/rect@0.10.5" has incorrect peer dependency "react-dom@^16.8.0".
warning "@reach/rect > @reach/utils@0.10.5" has incorrect peer dependency "react@^16.8.0".
warning "@reach/rect > @reach/utils@0.10.5" has incorrect peer dependency "react-dom@^16.8.0".
warning "next > styled-jsx > @babel/plugin-syntax-jsx@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "@typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] Building fresh packages...
error D:\PELATIHAN\tailwindcss.com\node_modules\deasync: Command failed.
Exit code: 1
Command: node ./build.js
Arguments:
Directory: D:\PELATIHAN\tailwindcss.com\node_modules\deasync
Output:
D:\PELATIHAN\tailwindcss.com\node_modules\deasync>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.14.2 | win32 | x64
gyp info find Python using Python version 3.10.5 found at "C:\Users\Ansharullah\AppData\Local\Programs\Python\Python310\python.exe"
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:384:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:406:5)
gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\PELATIHAN\tailwindcss.com\node_modules\deasync
gyp ERR! node -v v16.14.2
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok
Build failed
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by naveennamani** [comment]
Try using `yarn install --frozen-lockfile` instead of `yarn install`.
If that doesn't solve the issue, try to first remove `package-lock.json` and `yarn.lock` files if exists.
Then try to manually install deasync package using `yarn install deasync` or `npm install deasync`.
If the problem still persists with installation of deasync, you may need to downgrade your nodejs version as deasync package
doesn't come with binary for every nodejs version. You may get compatibility list here

https://github.com/abbr/deasync-bin

If the issue still persist, you can open an issue in `deasync` package repo with your OS, node version, npm version details.

Note: if you just want to have offline files, you can build them in a cloud environment like gitpod.io, then download the build files to your local machine and use python or serve package for browsing the docs. All scripts on this repo are tested in gitpod.io

**Comment by naveennamani** [comment]
Closing this issue as no there is no response.
