### ISSUE TITLE
Next JS

### ISSUE THREAD

**Issue by FreeCreativ** [naveennamani/offline-docs#18]

**Comment by naveennamani** [comment]
next.js docs are only available as markdown files and the documentation website is not open-source. If you want you can read the markdown files directly from here

https://github.com/vercel/next.js/tree/canary/docs

But, I think reading on the website gives you a better experience.

**Comment by naveennamani** [comment]
After going through the next.js repo discussions, I've found this thread and the documentation pdf link.

Please check.

https://github.com/vercel/next.js/discussions/35643

https://github.com/vercel/next.js/files/13780346/Next.js_v14_Documentation.pdf

**Comment by FreeCreativ** [comment]
Thank You Very Much Really Appreciate

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
