### ISSUE TITLE
Hacktoberfest 2022

### ISSUE THREAD

**Issue by naveennamani** [naveennamani/offline-docs#2]
For contributing to this project, please check the following dev.to post

https://dev.to/naveennamani/hacktoberfest-lets-contribute-to-my-project-offline-docs-60j

**Comment by rokaicker** [comment]
Hey! I was looking into adding Electron's docs to the project, but they build their site using docusaurus, and from my limited knowledge of the tool, it seems to require a server. Do you have a recommendation on how I should go about the script, considering I do have the .md files that make up the documentation? Thanks!

**Comment by naveennamani** [comment]
Hi @rokaicker, docusaurus is a static site generator tool, so there is no need for any server. You can run docusaurus build command for generating all the static HTML.

Please check https://github.com/naveennamani/offline-docs#react-native react native website which also uses docusaurus

**Comment by naveennamani** [comment]
@naninaveen @Nogueira-lucas @rokaicker

Thanks all for your contributions during the hacktoberfest. Hope to see your contributions even after the hacktoberfest.
